
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --


-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki


require("hypr_config/environment_variables")
require("hypr_config/autostart")
require("hypr_config/input")
if hl.get_config("input:kb_layout") == "fr" then
    require("hypr_config/binds_fr")
else
    require("hypr_config/binds_us")
end
require("hypr_config/misc")
require("hypr_config/animation")
require("hypr_config/windows_rule")

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
    output   = "eDP-1",
    mode     = "",
    position = "0x0",
    scale    = "1",
})
